import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import path from 'path';
import fs from 'fs';
const dir = path.dirname(new URL(import.meta.url).pathname);
fs.mkdirSync(path.join(dir, 'slides'), { recursive: true });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1080, height: 1920 } });
await p.goto('file://' + path.join(dir, 'carrousel.html'));
await p.evaluate(() => document.fonts.ready);
await p.waitForTimeout(500);
const n = await p.locator('section.slide').count();
for (let i = 0; i < n; i++) await p.locator('section.slide').nth(i).screenshot({ path: path.join(dir, 'slides', `slide_${i + 1}.png`) });
await b.close();
console.log('slides', n);
