import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import path from 'path';
const dir = path.dirname(new URL(import.meta.url).pathname);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1080, height: 1350 } });
await p.goto('file://' + path.join(dir, 'pub_structure.html'));
await p.evaluate(() => document.fonts.ready);
await p.waitForTimeout(300);
await p.locator('#root').screenshot({ path: path.join(dir, '../../../strategie-pub-meta/visuels/pub_image_fixe_v2_4x5.png') });
await b.close();
